### ISSUE TITLE
Elasticsearch fails to start due to RBAC list verb missing

### ISSUE THREAD

**Issue by solsson** [triggermesh/charts#11]
Applying 0.2.0 from #10, elasticsearch would fail to start with an error that it can't list namespaces.

The solution was to patch knative.yaml in a way that is easier said than `sed`ed:

```
--- knative/templates/knative.yaml.org  2018-11-05 15:36:03.000000000 +0100
+++ knative/templates/knative.yaml  2018-11-05 15:36:06.000000000 +0100
@@ -1526,6 +1526,7 @@
   - endpoints
   verbs:
   - get
+  - list
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
```

**Comment by solsson** [comment]
Note that the error only occurs with monitoring-elasticsearch enabled, i.e. with the following diff when the helm chart is built:

```
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -15,7 +15,7 @@ steps:
 
 # Get the Knative manifest
 - name: 'gcr.io/cloud-builders/wget'
-  args: ['-O', 'knative/templates/knative.yaml', 'https://github.com/knative/serving/releases/download/v0.2.0/release-no-mon.yaml']
+  args: ['-O', 'knative/templates/knative.yaml', 'https://github.com/knative/serving/releases/download/v0.2.0/release.yaml']

```

**Comment by cab105** [comment]
Based on research into another issue relating to this release, I stumbled upon this:
https://github.com/knative/serving/issues/2300

Perhaps something we'll want to keep in mind if we're not going to be using monitoring going forward.

**Comment by solsson** [comment]
Looks like this has been fixed in 0.2.1, based on quick tests with https://github.com/solsson/triggermesh-charts/tree/script-examples.

So maybe #15 fixes this, but we won't know because it uses `-no-mon` yaml :)

**Comment by cab105** [comment]
Has it? From the "cherry pick" notes it doesn't seem obvious unless it was a rerun of their regenerated yaml file.

**Comment by sebgoa** [comment]
closing because stale after 90 days
