### ISSUE TITLE
image missing

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/charts#7]
@solsson in your installer you show a k8s job that makes uses of an image: `gcr.io/triggermesh/knative-installer`

but where is this image coming from ? We are not building it yet

**Comment by solsson** [comment]
The second commit in https://github.com/triggermesh/charts/pull/9 should make the image available, assuming cloud-build's `PROJECT_ID` can be `triggermesh`

**Comment by solsson** [comment]
I built locally using https://github.com/triggermesh/charts/blob/master/installer/README.md#development which supports arbitrary image names.

**Comment by solsson** [comment]
Yes it is, `gcr.io/triggermesh/knative-installer:latest` as well as `gcr.io/triggermesh/knative-installer:0.1` and `gcr.io/triggermesh/knative-installer:0.2`.

**Comment by sebgoa** [comment]
ok, so I am closing this
